default: &default
  url: <%= ENV.fetch("KREDIS_URL") { "redis://127.0.0.1:6379/1" } %>

development:
  <<: *default

test:
  url: <%= ENV.fetch("KREDIS_URL") { "redis://127.0.0.1:6379/2" } %>

production:
  url: <%= ENV.fetch("KREDIS_URL") { ENV["KREDIS_URL"] || ENV["REDIS_URL"] || "redis://127.0.0.1:6379/0" } %>

